branch update and proposed changes
nurali-techie/fabric8-auth pull request #1
Opened 2019-04-29 12:46 UTC by xcoulon

2019-04-30 09:37 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_base.go
> +	os.Setenv("AUTH_CONFIG_FILE_PATH", "e2e_test_config.yml")
need to set it back after test with original value `AUTH_CONFIG_FILE_PATH`

2019-04-30 09:39 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_base.go
> +	s.stopAuth = func() {
`stopAuth` is unused, can be removed.

2019-04-30 09:45 UTC, xcoulon commented on test/integration/user_deactivation_e2e_base.go
> +	s.stopAuth = func() {
address in 973fe7a

2019-04-30 09:45 UTC, xcoulon commented on test/integration/user_deactivation_e2e_base.go
> +	os.Setenv("AUTH_CONFIG_FILE_PATH", "e2e_test_config.yml")
addressed in 973fe7a

2019-04-30 09:49 UTC, nurali-techie requested changes
@xcoulon I just try to run the test and it's timing out and both tests are failing.  Please fix it.

2019-04-30 09:52 UTC, xcoulon commented
ouch! They passed yesterday, so I guess that there was something wrong with the rebase or the latest changes :/ Let me check that!

2019-04-30 11:53 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_base.go
> +		rw.WriteHeader(http.StatusNoContent)
`StatusNoContent` is fine ?? previously I was returning `StatusOK` and I guess it was working fine.

2019-04-30 11:54 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_base.go
> +	log.Println(output.String())
`fmt` was intentional, we don't need to show log time when displaying auth_logs.

2019-04-30 12:01 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(25 * time.Second)
I am not sure what calc gives you timeout=25 seconds ??
If you see, `user.deactivation.interval.seconds` is 25 seconds, so it may be possible that test will timeout before deactivation_worker does it work.

2019-04-30 12:03 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(30 * time.Second)
same here, `user.deactivation.notification.interval.seconds` are 15 and we need to wait for two times for two notification.  What's calc logic and I wonder this test are not timing out now and then.

2019-04-30 12:03 UTC, xcoulon commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(25 * time.Second)
with `AUTH_RESOURCE_DATABASE=1 AUTH_USER_DEACTIVATION_NOTIFICATION_INTERVAL_SECONDS=5 AUTH_USER_DEACTIVATION_INTERVAL_SECONDS=10 AUTH_DEVELOPER_MODE_ENABLED=true AUTH_USER_DEACTIVATION_ENABLED=true AUTH_USER_DEACTIVATION_NOTIFICATION_ENABLED=true go test github.com/fabric8-services/fabric8-auth/test/integration -v -run TestUserDeactivation/` the deactivation runner worker would have the time to perform 2 cycles and the deactivation notification 4 or 5 cycles. But I'm fine with restoring to `40s` if you prefer. It's just a matter of waiting longer for the test to end

2019-04-30 12:03 UTC, xcoulon commented on test/integration/user_deactivation_e2e_base.go
> +	log.Println(output.String())
what do you mean by that exactly?

2019-04-30 12:04 UTC, xcoulon commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(30 * time.Second)
see comment above. I was using custom settings during the test.

2019-04-30 12:05 UTC, xcoulon commented on test/integration/user_deactivation_e2e_base.go
> +		rw.WriteHeader(http.StatusNoContent)
see https://github.com/fabric8-services/fabric8-auth/blob/master/che/service/che_service.go#L73

2019-04-30 12:06 UTC, xcoulon commented
For the record, both tests pass with the following command:
```
AUTH_RESOURCE_DATABASE=1 AUTH_USER_DEACTIVATION_NOTIFICATION_INTERVAL_SECONDS=5 AUTH_USER_DEACTIVATION_INTERVAL_SECONDS=10 AUTH_DEVELOPER_MODE_ENABLED=true AUTH_USER_DEACTIVATION_ENABLED=true AUTH_USER_DEACTIVATION_NOTIFICATION_ENABLED=true go test github.com/fabric8-services/fabric8-auth/test/integration -v -run TestUserDeactivation/
```

2019-04-30 12:07 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(25 * time.Second)
I have run multiple time and found auth_service sometimes takes time to start and in such case having long notification_interval helped.  Please don't change this until and unless you have strong reason to do so.  While creating this test, I have run it so many times and come to these values now for few run you may get success with lesser delay but it may not be enough which what I observed.

Also, there is `e2e_test_config.yml` file, where all these interval are there.  If you don't want to use those values then please remove from the config file.

2019-04-30 12:10 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(25 * time.Second)
I really don't see any reason for this optimization, it's good to be safe than optimized (these are tests and not production code).

2019-04-30 12:11 UTC, xcoulon commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(25 * time.Second)
I found that 25s was enough to get the test to pass and I did not have to wait another extra 15s before the test ended, that's all. But I'll revert those timeout settings

2019-04-30 12:12 UTC, xcoulon commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(25 * time.Second)
reverted in 64d53f9

2019-04-30 12:12 UTC, xcoulon commented on test/integration/user_deactivation_e2e_test.go
> +	timeout := time.NewTimer(30 * time.Second)
reverted in 64d53f9

2019-04-30 12:16 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_base.go
> +	log.Println(output.String())
minor comment can be ignored.
`fmt` just print auth_logs.
`log` gives log time_date and print auth_logs.
please run both and compare output.

2019-04-30 12:18 UTC, xcoulon commented on test/integration/user_deactivation_e2e_base.go
> +	log.Println(output.String())
ok. Feel free to revert if you prefer, but reading the code and seeing a mix of `fmt.Print` and `log.Println` looked weird at first sight.

2019-04-30 12:36 UTC, nurali-techie commented on test/integration/user_deactivation_e2e_test.go
> +	s.updateLastActive(identity, ago40days)
why we are updating last_active by calling `updateLastActive()` ??
I was expecting the http_call will do this work.
If we are directly calling `updateLastActive()` then what's the point of making http_call `ExchangeToken` ??

2019-05-03 07:32 UTC, nurali-techie approved these changes

2019-05-03 07:33 UTC, merged